### ISSUE TITLE
[BUG] Termination condition for Contact Primitive

### ISSUE THREAD

**Issue by yellownebula10** [flexivrobotics/flexiv_rdk#65]
**Version information**
- RDK: v0.10
- Robot software: v2.10.9
- OS: macOS 14.5 - arm64

**Describe the bug**
When polling primitive states to determine that the contact primitive has terminated, if the termination condition is set to 'terminated' == '1' as specified by the [primitives documentation](https://original.flexiv.com/en/primitives/Basic%20Force%20Control.html#id6), the condition is never met.

**Steps to reproduce**
1. Send contact primitive to robot with default parameters
2. Add a while loop polling current primitive states, checking for 'terminated' == '1'
3. See error

**Expected behavior**
The primitive state 'terminated' should be set to '1'. However, when I print the primitive states as the primitive executes, I notice that ‘terminated’ remains at ‘0’ while ‘primitiveName’ switches to ‘Hold’ from ‘Contact’ and ‘reachedTarget’ is set equal to ‘1’.

**Screenshots**
<img width="1512" alt="Screenshot 2024-06-07 at 5 16 58 PM" src="https://github.com/flexivrobotics/flexiv_rdk/assets/173857080/d9cc8bcf-4bb4-444f-9d5c-8f5159c71e5a">

**Comment by kaibiao-flexiv** [comment]
Hi @yellownebula10 ,

In our system, some primitives have a self-termination condition, which means that when the termination condition is met, the primitive will automatically terminate. The Contact primitives you mentioned are among those primitives that can self-terminate. (This is because after contact is made, the robot should not be staying within Contact primitive state)

So the reason that you were not able to reach the 'terminated' == '1'' condition is because at the time you query, the primitive has already met the self-termination condition and has already exited, and the primitive states are no longer available as that primitive is no longer running.

To identify which primitives will terminate by itself: 
If you spot the primitive's default transition condition is [terminated == 1], then this means it is one of the self-terminated primitives [Flexiv Primitives default transition condition](https://original.flexiv.com/en/primitives/Basic%20Force%20Control.html?#default-transition-condition)
![image](https://github.com/flexivrobotics/flexiv_rdk/assets/172339931/4ee8d86c-08a3-4d11-8531-1aa43ea35e5d)

To check if such primitives are terminated or not, you can use the isBusy() method, below is an example code snippet:
![image](https://github.com/flexivrobotics/flexiv_rdk/assets/172339931/182f3e9b-eeef-4b1a-a3c8-ad875f9ac27f)

**Comment by yellownebula10** [comment]
Thank you @kaibiao-flexiv !
