### ISSUE TITLE
[BUG] Robot::busy() gives false negative

### ISSUE THREAD

**Issue by isa-9** [flexivrobotics/flexiv_rdk#76]
**Version information**
- RDK: v1.4
- Robot software: v3.6

**Describe the bug**
`Robot::busy()` seems to be not be updated to actual state of the robot after calling `Robot.ExecutePlan()`. When running the example `basics4_plan_execution.py`, it doesn't print anything unless there is a `time.sleep(...)` between the call of  `Robot.ExecutePlan()` and `Robot::busy()`.

**Additional context**
"I tested various values for `time.sleep()` and found that `Robot::busy()` returned False with a delay of 0.121 seconds, but returned True with a delay of 0.122 seconds or more."

**Comment by pzhu-flexiv** [comment]
@isa-9 After a plan/primitive command is sent to the robot, it takes some time for the robot to load the command and compute trajectory before actually start executing. During this preparation period (varies from 10ms to 200ms depends on the complexity of the command and trajectory computation), `Robot::busy()` will return false because the execution is not started yet.

We used to have forced 200ms wait in `ExecutePlan()` and `ExecutePrimitive()`, but it did not turn out to be an optimal solution as some customers want short-blocking function calls. Thus, we removed the forced wait, and give the flexibility back to the user.

We will add a warning note to `Robot::busy()` stating that a wait is required after calling to `ExecutePlan()` and `ExecutePrimitive()` before `busy()` can return the correct status.
